name: My first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v7

            - name: welcome message with list files and read
              run: | 
               echo "Hello my first workflow"
               ls -ltra
               cat README.md
            
            
              #- name: list files
             # run: ls
            #- name: read file
             # run: cat README.md
        