name: variable and secrets
on: workflow_dispatch

env:
  CONTAINER_REGISTRY: docker.io
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
      - name: Docker build
        run: echo "docker build -t ${{ env.CONTAINER_REGISTRY }}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest"

      - name: Docker Login
        run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest

  deploy:
    needs: docker
    concurrency: 
      group: deploy
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: check repo
        uses: actions/checkout@v7
      - name: Docker Run
        run: |
          echo docker run -d -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest
          sleep 500s